app/affiliate/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, BooleanField
from wtforms.validators import DataRequired, Length,  Regexp
from app.auth.validation import usernames


class AffiliateSignup(FlaskForm):

    username = StringField('Username', validators=[
        DataRequired(message='Vendor Signature is Required'),
        Length(1, 50),
        Regexp(usernames)])

    agreement = BooleanField(default=False)
    submit = SubmitField()

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)

    def validate(self):

        rv = FlaskForm.validate(self)
        if rv:
            return True
        else:
            return False


class AffiliateCode(FlaskForm):

    thecode = StringField(validators=[
        DataRequired(message='A code is required'),
        Length(5, 15),
        Regexp(usernames)])

    submit = SubmitField()

    def __init__(self, *args, **kwargs):
        FlaskForm.__init__(self, *args, **kwargs)

    def validate(self):

        rv = FlaskForm.validate(self)
        if rv:
            return True
        else:
            return False

app/affiliate/__init__.py
# coding=utf-8
__author__ = 'eeamesX'
from flask import Blueprint

affiliate = Blueprint('affiliate', __name__)

from . import views

app/affiliate/views.py
from flask import render_template, redirect, url_for, flash, request
from flask_login import current_user
from app.affiliate import affiliate
from app import db

from datetime import datetime
# forms
from app.affiliate.forms import \
    AffiliateSignup, \
    AffiliateCode

# models
from app.classes.affiliate import Affiliate_Orders
from app.classes.auth import Auth_User

from app.classes.affiliate import Affiliate_Overview, \
    Affiliate_Stats, \
    Affiliate_Id

from app.common.decorators import \
    website_offline, \
    login_required


@affiliate.route('/overview', methods=['GET'])
@website_offline
def aff_overview():
    return render_template('/affiliate/overview.html')


@affiliate.route('/signup', methods=['GET', 'POST'])
@login_required
@website_offline
def aff_become_aff():
    now = datetime.utcnow()
    vendorsignupForm = AffiliateSignup()
    user = db.session.query(Auth_User).filter_by(
        username=current_user.username).first()

    if request.method == 'POST':

        if vendorsignupForm.validate_on_submit():
            if user.username == vendorsignupForm.username.data:
                if vendorsignupForm.agreement.data is True:

                    affaccount_overview = Affiliate_Overview(
                        user_id=user.id,
                        buyerdiscount=2.5,
                        buyerdiscount_time=now,
                        aff_fee=2.5,
                        aff_fee_time=now,
                        aff_link_1='',
                        aff_link_2='',
                    )

                    affaccount_stats = Affiliate_Stats(
                        user_id=user.id,
                        promocode='',
                        totalitemsordered=0,
                        promoenteredcount=0,
                        btc_earned=0,
                        btc_cash_earned=0,

                    )
                    db.session.add(affaccount_stats)
                    db.session.add(affaccount_overview)
                    db.session.commit()

                    user.affiliate_account = affaccount_overview.user_id
                    db.session.add(user)
                    db.session.commit()

                    flash("Welcome as a protos Affiliate",
                          category="success")
                    return redirect(url_for('affiliate.aff_home'))
                else:
                    flash("Please accept the agreement", category="danger")
                    return redirect(url_for('affiliate.aff_become_aff'))
            else:
                flash("invalid username", category="danger")
                return redirect(url_for('affiliate.aff_become_aff'))
        else:
            flash(vendorsignupForm.errors, category="danger")
            return redirect(url_for('affiliate.aff_become_aff'))

    return render_template('/affiliate/homecontent/becomeaff.html',
                           vendorsignupForm=vendorsignupForm)


@affiliate.route('/home', methods=['GET', 'POST'])
@login_required
@website_offline
def aff_home():
    now = datetime.utcnow()
    promocodeform = AffiliateCode()

    # users promo overview
    userpromooverview = db.session.query(
        Affiliate_Overview).filter_by(user_id=current_user.id).first()
    # users promo stats
    userpromostats = db.session.query(Affiliate_Stats).filter_by(
        user_id=current_user.id).first()
    # users promo code

    userpromocode = db.session.query(Affiliate_Id).filter_by(
        user_id=current_user.id).first()
    if userpromocode is not None:
        # get last 20 affiliates orders..
        latest_affiliates = db.session.query(Affiliate_Orders).filter(
            Affiliate_Orders.affiliate_code == userpromocode.promocode).order_by(Affiliate_Orders.id.desc()).limit(20)
    else:
        latest_affiliates = None

    if request.method == 'POST':
        if promocodeform.submit.data:
            if promocodeform.validate_on_submit():
                if userpromocode is None:
                    seeifpromoexists = db.session.query(Affiliate_Id).filter_by(
                        promocode=promocodeform.thecode.data).first()
                    if seeifpromoexists is None:
                        newpromocode = Affiliate_Id(
                            user_id=current_user.id,
                            promocode=promocodeform.thecode.data)

                        userpromooverview.promocode = promocodeform.thecode.data
                        userpromostats.promocode = promocodeform.thecode.data

                        db.session.add(userpromooverview)
                        db.session.add(newpromocode)
                        db.session.commit()
                        flash("Success creating promo code", category="success")
                        return redirect(url_for('affiliate.aff_home'))
                    else:
                        flash("Code exists, try another..", category="danger")
                        return redirect(url_for('affiliate.aff_home'))
                else:
                    flash("Cant create code, you already have one",
                          category="danger")
                    return redirect(url_for('affiliate.aff_home'))
            else:
                flash(
                    "Form error.  5-15 characters.  No special characters.", category="danger")
                return redirect(url_for('affiliate.aff_home'))

    return render_template('/affiliate/home.html',
                           now=now,
                           userpromooverview=userpromooverview,
                           promocodeform=promocodeform,
                           userpromocode=userpromocode,
                           userpromostats=userpromostats,
                           latest_affiliates=latest_affiliates,
                           )


@affiliate.route('/images', methods=['GET', 'POST'])
@login_required
@website_offline
def aff_images():
    now = datetime.utcnow()

    return render_template('/affiliate/affimages.html',
                           now=now,
                           )

app/templates/affiliate/affimages.html
{% extends "/layouts/plain.html" %}
{% block content %}


    <nav aria-label="breadcrumb" class="linkcolor">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('index') }}">Home</a></li>

        </ol>
    </nav>

    <div class="row" style="margin-bottom: 50px;">
        {% include '/affiliate/homecontent/_bannertop.html' %}
    </div>
    <div class="row text-center">
        <div class="col-12 ">
            Using images helps attract users to click on your promo ad.
        </div>

    </div>
    <div class="row text-center">
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img src="{{ url_for('static', filename='/images/affiliate/afflogo4.png')  }}">
        </div>
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img src="{{ url_for('static', filename='/images/affiliate/afflogo5.png')  }}">
        </div>
    </div>
     <div class="row text-center">
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img src="{{ url_for('static', filename='/images/affiliate/afflogo1.png')  }}">
        </div>
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img class='border' src="{{ url_for('static', filename='/images/affiliate/afflogo3.png')  }}">
        </div>
     </div>
     <div class="row text-center">
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img class='border' src="{{ url_for('static', filename='/images/affiliate/afflogo2.png')  }}">
        </div>
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img class='border' src="{{ url_for('static', filename='/images/affiliate/afflogo8.png')  }}">
        </div>
     </div>
     <div class="row text-center">
        <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img class='border' src="{{ url_for('static', filename='/images/affiliate/afflogo9.png')  }}">
        </div>

     </div>
    <div class="row">
    <div class="col-12 col-sm-6 col-sm-offset-3">
                <div class="col-12 col-sm-6" style="margin-bottom: 25px">
            <img class='border' src="{{ url_for('static', filename='/images/affiliate/afflogo7.png')  }}">
        </div>
    </div>
    </div>
{% endblock %}



app/templates/affiliate/home.html
{% extends "/layouts/plain.html" %}
{% block content %}


    <nav aria-label="breadcrumb" class="linkcolor">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('index') }}">Home</a></li>

        </ol>
    </nav>

    <div style="margin-bottom: 50px;">
        {% include '/affiliate/homecontent/_bannertop.html' %}
    </div>
    <div class="row">
        <div class="col-12 text-center linkcolor" style="margin-bottom: 25px;">
            Using images helps attract users to click on your promo ad.
            <a href="{{ url_for('affiliate.aff_images') }}">
                Find images to use for your site like the one below
                <img src="{{ url_for('static', filename='/images/affiliate/afflogo1.png')  }}" width="325px" height="325px">
            </a>
        </div>
    </div>
    <div class="row border graybg" style="margin-bottom: 50px; padding: 10px;">
        <div class="col-12 text-left">
            {% if userpromocode == None %}
                <form method="post">
                    {{ promocodeform.csrf_token }}
                    <div class="row">
                        <div class="form-group">
                            <label class="col-12 col-sm-4 col-sm-offset-4">Create A Promo Code</label>
                            <div class="col-12 col-sm-4 col-sm-offset-4">
                                {{ render_field(promocodeform.thecode, class="form-control") }}
                            </div>
                            <div class="col-12 col-sm-4 col-sm-offset-4" style="font-size: 10px; margin-bottom: 20px;">
                                5-15 character long code.  Make it easy to understand so people remember.  Cannot
                                be changed.
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-12 text-center">
                            {{ render_field(promocodeform.submit, class="btn btn-warning", value="Create Code") }}
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="text-center"><h4><b>Promo Code:</b> {{ userpromocode.promocode }}<br></h4></div>

                <b>Status:</b> Affiliate Active <br><br>
                <b>Buyer Discount:</b> {{ userpromooverview.buyerdiscount }} %<br>
                <b>Your Profit/per order:</b> {{ userpromooverview.aff_fee }} %<br>
                <br>
                <h4>Stats</h4>
                <b>Total Orders:</b> {{ userpromostats.totalitemsordered }}<br>

                <b>Promo Entered Count:</b> {{ userpromostats.promoenteredcount }}<br>
                <br>
                <h4>BTC</h4>

                <b>BTC earned:</b>
                {% if userpromostats.btc_earned == 0%}
                    <div class="btcorange">  0 BTC</div>
                {% else %}
                    <div class="btcorange"> {{ userpromostats.btc_earned }} BTC</div>
                {% endif %}
                <br>

                <br>
                <h4>BCH</h4>
                <b>BCH earned:</b>
                {% if userpromostats.btc_cash_earned == 0%}
                    <div class="btccash"> 0 BCH</div>
                {% else %}
                    <div class="btccash"> {{ userpromostats.btc_cash_earned }} BCH</div>
                {% endif %}
                <br>
            {% endif %}
        </div>
    </div>



    <h4>Promo Codes Used on Orders</h4>
    <table class="table col-12">
        <tr>
            <th class="bluetable col-1">Order ID</th>
            <th class="bluetable col-2">Age</th>
            <th class="bluetable hidden-xs col-sm-3">Customer</th>
            <th class="bluetable col-3">Item</th>
            <th class="bluetable col-3">Profit</th>
        </tr>
        {% if userpromocode == None %}
            <tr>
                <td class="col-12 text-center" style="margin-top: 25px; font-size: 18px">You do not have a promo code </td>
            </tr>
        {% else %}
            {% for promoorder in latest_affiliates %}
                <tr>
                    <td class="col-1">
                        {{ promoorder.id }}
                    </td>
                    <td class="col-2">
                        {{ moment(timestamp=promoorder.age, local=False).fromTime(now)  }}
                    <td class="col-3">
                        {{ promoorder.customer }}
                        ({{ promoorder.customer_id|userrating }})
                        ({{ promoorder.customer_id|avguserrating }}
                        <img src="{{ url_for('static', filename='/images/stars/1s.png'  )  }}"
                             width="15px" height="15px">)
                    </td>
                    <td class="hidden-xs col-sm-4 linkcolor">
                        <a href="{{ url_for('item.item_for_sale',id=promoorder.item_id) }}">
                            {{ promoorder.title }}
                        </a>
                    </td>
                    <td class="col-6 col-sm-2">
                        {% if promoorder.affiliate_discount_btc == 0%}

                        {% else %}

                            <div class="btcorange"> {{ promoorder.affiliate_profit }} BTC</div>
                        {% endif %}


                        {% if promoorder.affiliate_discount_btc_cash == 0%}

                        {% else %}
                            <div class="btccash"> {{ promoorder.affiliate_profit }} BTC</div>
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        {% endif %}
    </table>


{% endblock %}



app/templates/affiliate/overview.html
{% extends "/layouts/plain.html" %}
{% block content %}


    <nav aria-label="breadcrumb" class="linkcolor">
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="{{ url_for('index') }}">Home</a></li>

        </ol>
    </nav>

        <div class="row" style="margin-bottom: 50px;">
            <div class="col-12 text-center">
                <h3>Protos Affiliate</h3>
            </div>
        </div>
        <div style="margin-bottom: 50px;">
            {% include '/affiliate/homecontent/_bannertop.html' %}
        </div>

        <div class="row" style="margin-bottom: 50px;">
            <div class="col-12 text-left">
                <h4>How does it work?</h4>
                <span>After you signup, you are given a promo code. The promo code can be given to people to be used
                on checkout.  The buyer discount ranges between 1%-5% depending on your affiliate status.
                    You are given a percentage fee for each transaction.</span>
                <br><br>
                <h4>How much can I make?</h4>
                <span>This depends on how many sales, your affiliate status, etc.  There is no limit
                to the amount you can earn, or cap.  </span>
                <br><br>
                <h4>How do I get paid?</h4>
                <span>After each sale is finalized,
                    the percent of your promo code discount is funded immediatly to your account.
                </span>
                <br><br>

            </div>
        </div>

        <div class="row" style="margin-bottom: 50px;">
            <div class="col-12 text-center">
               <a class="btn btn-primary" href="{{ url_for('affiliate.aff_become_aff') }}">Become Affiliate</a>
            </div>
        </div>



{% endblock %}

